import html
import time
import os
from flask import Flask, flash, request, redirect, url_for, render_template, Response
from werkzeug.utils import secure_filename
from flask import send_from_directory , Markup
import subprocess
import pickle
from redis import Redis
import rq

ROOT_FOLDER = os.path.dirname(os.path.realpath(__file__)) 
UPLOAD_FOLDER = ROOT_FOLDER + '/uploads'
ALLOWED_EXTENSIONS = set(['txt', 'faa', 'fasta', 'gif', 'fa'])
import urllib

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['APPLICATION_ROOT']=''
PREFIX=app.config['APPLICATION_ROOT'] 

def fix_url_for(path, **kwargs):
    return PREFIX + url_for(path, **kwargs)


#make fix_url_for available in tamplates
@app.context_processor
def contex():
    return dict(fix_url_for = fix_url_for)

#add the sorable attribute to tables generated by pandas
@app.template_filter('sorttable')
def sorttable_filter(s):
    s= s.replace('table id=','table class="sortable" id=')
    return s


def return_html_table(filename):
    cmd = ["python" , "run_tri_model.py" , app.config['UPLOAD_FOLDER'] + '/' + filename]
    p = subprocess.Popen(cmd, stdout = subprocess.PIPE,
                         stderr=subprocess.PIPE,
                         stdin=subprocess.PIPE)
    out,err = p.communicate()
    print(err)
    return out


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@app.route('/bar/<filename>')
def bar(filename):
    return render_template('loading.html',filename=filename)


@app.route('/progress/<filename>')
def progress(filename):
    #yield "data:0" + "\n\n"
    #yield "event:url" + "\n" + "data:'http://0.0.0.0:8080/upload'" + "\n\n"
    
    
    #yield "event: url\ndata: {\"url\":\"http://0.0.0.0:8080/upload\"}\n\n"
    queue = rq.Queue('microblog-tasks', connection=Redis.from_url('redis://'))
    job = queue.enqueue('run_tri_model_app.entrypoint',23)
    seq_total=49
    def generate():
        yield "event: url\ndata: {\"url\":\"http://0.0.0.0:8080/saves" + '/' + filename + "\"}\n\n"
        while not job.is_finished:
            job.refresh()
            try:
                seq_total=job.meta['total']
            except:
                seq_total=1
            try:
                seq_current=job.meta['current']
            except:
                seq_current=0
            data=(seq_current/seq_total) * 100
            yield "event: update\ndata:" + str(data) + "\n\n"
            time.sleep(0.02)
            print(data)
  #          print("data:" + url_fix_for('saves') + 'A45_phage_orfs.txt' + "\n\n")
    
    return Response(generate(), mimetype= 'text/event-stream')

@app.route('/test')
def test_template():
    return "mira un salmon"

@app.route('/', methods=['GET', 'POST'])
@app.route('/upload', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            print( fix_url_for('upload_file',filename=filename))
            return redirect(fix_url_for('uploaded_file',
                                    filename=filename))
    print( fix_url_for('upload_file'))
    return render_template('main.html')

@app.route('/about')
def about():
    return render_template('about.html', title='about')

@app.route('/uploads/<filename>')
def uploaded_file(filename):
    table_code_raw= Markup(return_html_table(filename).decode('utf8'))
    table=render_template('index.html', table_code= table_code_raw)
    pickle.dump(table_code_raw,open('saves/' + filename,"wb"))
    return table

@app.route('/saves/<filename>')
def show_file(filename):
    table_code_raw=pickle.load(open('saves/' + filename,"rb"))
    return render_template('index.html', table_code= table_code_raw)

@app.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(app.root_path, 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=8080)
    #app.run(host="0.0.0.0", port=8080)
